/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2;

import static examen2.Banco.listaCuenta;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PAUL PASACA
 */
public class EXAMEN2PRINCIPAL extends javax.swing.JFrame {

    Banco banco = new Banco();
    String archivo="" ;

    /**
     * Creates new form CuentaA
     */
    public EXAMEN2PRINCIPAL() {
        initComponents();
        this.setLocationRelativeTo(null);
        buscar.setEnabled(false);
        retiro.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        nuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        interes = new javax.swing.JTextField();
        tipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        retiro = new javax.swing.JButton();
        tipoP = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Examen 2");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Cuenta Bancaria");

        nuevo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nuevo.setText("Ingresar");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        jLabel2.setText("NOMBRE");

        jLabel3.setText("TIPO");

        jLabel4.setText("BALANCE");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel5.setText("INTERES");

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CuentaAhorros", "CuentaPrestamo", "CuentaHipoteca" }));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Lista");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscar.setText("Depositar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        retiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        retiro.setText("Retirar");
        retiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retiroActionPerformed(evt);
            }
        });

        tipoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural", "Empresa", " " }));

        jLabel6.setText("CUENTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(114, 114, 114))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(buscar)
                        .addGap(63, 63, 63)
                        .addComponent(retiro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(tipoP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel6))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(interes, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(interes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retiro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        String t = (String) this.tipo.getSelectedItem();
        if (t.equalsIgnoreCase("CuentaAhorros")) {
            buscar.setEnabled(true);
            retiro.setEnabled(true);

            CuentaAhorro c;
            double b = Double.parseDouble(this.balance.getText());
            double i = Double.parseDouble(this.interes.getText());
            c = new CuentaAhorro(this.nombre.getText(), (String) this.tipoP.getSelectedItem(), b, i);
            banco.agregar(c);
        }
        if (t.equalsIgnoreCase("CuentaHipoteca")) {
            buscar.setEnabled(true);
            retiro.setEnabled(false);
            CuentaHipoteca cH;
            double b1 = Double.parseDouble(this.balance.getText());
            double i1 = Double.parseDouble(this.interes.getText());
            cH = new CuentaHipoteca(this.nombre.getText(), (String) this.tipoP.getSelectedItem(), b1, i1);
            banco.agregar(cH);
        }
        if (t.equalsIgnoreCase("CuentaPrestamo")) {
            buscar.setEnabled(true);
            retiro.setEnabled(false);
            CuentaHipoteca cP;
            double b2 = Double.parseDouble(this.balance.getText());
            double i2 = Double.parseDouble(this.interes.getText());
            cP = new CuentaHipoteca(this.nombre.getText(), (String) this.tipoP.getSelectedItem(), b2, i2);
            banco.agregar(cP);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_nuevoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        banco.presentar();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String n = this.nombre.getText();
        Cuenta cc = depositar(n);

        JOptionPane.showMessageDialog(null, cc);

        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void retiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiroActionPerformed

        String n = this.nombre.getText();
        Cuenta cr = retirar(n);
        JOptionPane.showMessageDialog(null, cr);

// TODO add your handling code here:
    }//GEN-LAST:event_retiroActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            grabar();
        } catch (IOException ex) {
            Logger.getLogger(EXAMEN2PRINCIPAL.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            leer();// TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(EXAMEN2PRINCIPAL.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed
    public void grabar() throws IOException {
        
        FileWriter fw = new FileWriter(new File(archivo + ".csv"));
        try {

            for (Cuenta cuenta : listaCuenta) {
                if (cuenta instanceof CuentaAhorro) {
                    fw.write("Cuenta Ahorro" + ";" + cuenta + "\n");
                }
                if (cuenta instanceof CuentaHipoteca) {
                    fw.write("Cuenta Hipoteca" + ";" + cuenta + "\n");
                }
                if (cuenta instanceof CuentaPrestamo) {
                    fw.write("Cuenta Prestamo" + ";" + cuenta + "\n");
                }

            }
            fw.close();
        } catch (IOException e) {
        }
    }

    public Cuenta depositar(String n) {
        for (Cuenta cuenta : listaCuenta) {
            if (n.equalsIgnoreCase(cuenta.getCliente())) {
                int d = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese cantidad a depositar"));
                cuenta.setBalance(cuenta.getBalance() + d);
                return cuenta;
            }
        }
        return null;
    }

    public Cuenta retirar(String n) {

        for (Cuenta cuenta : listaCuenta) {
            if (n.equalsIgnoreCase(cuenta.getCliente())) {
                if (cuenta instanceof CuentaHipoteca) {

                    break;
                } else {
                    int d = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese cantidad a retirar"));
                    cuenta.setBalance(cuenta.getBalance() - d);
                    return cuenta;
                }

            }
        }
        return null;
    }

    public void leer() throws IOException {
        String cadena;
        archivo = JOptionPane.showInputDialog(null, "Ingrese Direccion del archivo");
        FileReader f = new FileReader(new File(archivo + ".csv"));
        BufferedReader b = new BufferedReader(f);
        String lista[] = new String[4];

        while ((cadena = b.readLine()) != null) {
            String l[] = cadena.split(";");
            System.out.println(l[0]);

            if (l[0].equalsIgnoreCase("Cuenta Ahorro")) {

                String x1[] = l[1].split(",");
                for (int i = 0; i < 4; i++) {
                    String x2[] = x1[i].split("=");

                    lista[i] = x2[1];
                }
                CuentaAhorro c;
                double lb = Double.parseDouble(lista[2]);
                double li = Double.parseDouble(lista[3]);
                c = new CuentaAhorro(lista[0], lista[1], lb, li);
                banco.agregar(c);

            }
            if (l[0].equalsIgnoreCase("Cuenta Hipoteca")) {
                CuentaHipoteca cH;
                String x1[] = l[1].split(",");
                for (int i = 0; i < 4; i++) {
                    String x2[] = x1[i].split("=");

                    lista[i] = x2[1];
                }
                CuentaAhorro c;
                double lb = Double.parseDouble(lista[2]);
                double li = Double.parseDouble(lista[3]);

                cH = new CuentaHipoteca(lista[0], lista[1], lb, li);
                banco.agregar(cH);
            }
            if (l[0].equalsIgnoreCase("Cuenta Prestamo")) {
                CuentaHipoteca cP;
                String x1[] = l[1].split(",");
                for (int i = 0; i < 4; i++) {
                    String x2[] = x1[i].split("=");

                    lista[i] = x2[1];
                }
                CuentaAhorro c;
                double lb = Double.parseDouble(lista[2]);
                double li = Double.parseDouble(lista[3]);

                cP = new CuentaHipoteca(lista[0], lista[1], lb, li);
                banco.agregar(cP);
            }
        }
        b.close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EXAMEN2PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EXAMEN2PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EXAMEN2PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EXAMEN2PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EXAMEN2PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balance;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField interes;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton retiro;
    private javax.swing.JComboBox<String> tipo;
    private javax.swing.JComboBox<String> tipoP;
    // End of variables declaration//GEN-END:variables
}
